//! Moves `jobs` and `examples` onto UUIDv7 primary keys.
//!
//! A sequence leaks how many rows exist and lets anyone walk the table by
//! guessing the next number. UUIDv7 keeps the ordering a sequence gave us,
//! because the first 48 bits are a millisecond timestamp, so index locality
//! survives the change.
//!
//! Existing rows are backfilled here in Rust with the same generator the
//! application uses, rather than a hand written plpgsql function.

use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::{ConnectionTrait, Statement};
use uuid::Uuid;

/// Tables that carry a generated primary key, with the column that holds it.
const TABLES: [&str; 2] = ["jobs", "examples"];

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let connection = manager.get_connection();

        for table in TABLES {
            // Add the new column, fill it row by row, then swap it in. Doing it
            // in this order keeps the old ids readable while the swap runs.
            connection
                .execute_unprepared(&format!(
                    r#"ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "uuid_id" uuid"#
                ))
                .await?;

            let rows = connection
                .query_all_raw(Statement::from_string(
                    manager.get_database_backend(),
                    format!(r#"SELECT id FROM "{table}" WHERE "uuid_id" IS NULL ORDER BY id"#),
                ))
                .await?;

            for row in rows {
                let id: i64 = row.try_get_by_index(0).or_else(|_| {
                    row.try_get_by_index::<i32>(0).map(i64::from)
                })?;

                connection
                    .execute_raw(Statement::from_sql_and_values(
                        manager.get_database_backend(),
                        format!(r#"UPDATE "{table}" SET "uuid_id" = $1 WHERE id = $2"#),
                        [Uuid::now_v7().into(), id.into()],
                    ))
                    .await?;
            }

            connection
                .execute_unprepared(&format!(
                    r#"
                    ALTER TABLE "{table}" ALTER COLUMN "uuid_id" SET NOT NULL;
                    ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{table}_pkey";
                    ALTER TABLE "{table}" DROP COLUMN "id";
                    ALTER TABLE "{table}" RENAME COLUMN "uuid_id" TO "id";
                    ALTER TABLE "{table}" ADD PRIMARY KEY ("id");
                    "#
                ))
                .await?;
        }

        // The claim query reads by channel, status and due time, and the index
        // was dropped along with the old column ordering.
        connection
            .execute_unprepared(
                r#"CREATE INDEX IF NOT EXISTS "jobs_claim_idx" ON jobs (channel, status, available_at)"#,
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let connection = manager.get_connection();

        for table in TABLES {
            connection
                .execute_unprepared(&format!(
                    r#"
                    ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{table}_pkey";
                    ALTER TABLE "{table}" DROP COLUMN "id";
                    ALTER TABLE "{table}" ADD COLUMN "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                    "#
                ))
                .await?;
        }

        Ok(())
    }
}
